# Generated by Django 5.0.2 on 2024-02-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('task_description', models.TextField()),
                ('estimated_time', models.FloatField(blank=True, null=True)),
                ('worked_time', models.FloatField(blank=True, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='completed')),
            ],
        ),
    ]
