# Generated by Django 5.0.2 on 2024-02-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_task_estimated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='estimated_time',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='worked_time',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
